name: CI

on:
  push:
    branches: [ release/* ]
  pull_request:
    branches: [ release/* ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
            
      - name: Install dependencies
        run: dotnet restore ./src

      - id: get_version
        uses: battila7/get-version-action@v2
      
      - name: Show version
        run: echo ${{ steps.get_version.outputs.version }}
      
      - name: Build
        run: dotnet build --configuration Release --no-restore ./src /p:PackageVersion=${{ steps.get_version.outputs.version-without-v }}

      - name: Pack for NuGet
        run: dotnet pack  --configuration Release --no-build ./src/devCrowd.CustomBindings.EventSourcing.csproj -o . /p:PackageVersion=${{ steps.get_version.outputs.version-without-v }}

      - name: Publish to NuGet
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{secrets.EventSourcing_Nuget_ApiKey}} --skip-duplicate --no-symbols 1

